---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
  namespace: prod
spec:
  backendType: systemManager
  data:
    - key: /clincard/prod/couchpass
      name: password
