---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secrets
  namespace: prod
spec:
  backendType: systemManager
  data:
    - key: /clincard/prod/couchdb_secrets
      name: SecureString
