---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: peoples-trust-ftp
  namespace: prod
spec:
  backendType: systemManager
  data:
    - key: /clincard/prod/peoples_trust_ftp_user
      name: username
    - key: /clincard/prod/peoples_trust_ftp_password
      name: password
