---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rabbit-secret
  namespace: prod
spec:
  backendType: systemManager
  data:
    - key: /clincard/prod/rabbit_userpass
      name: payments
    - key: /clincard/prod/rabbit_userpass
      name: celery
