apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: redis
  namespace: prod
spec:
  backendType: systemManager
  data:
    - key: /clincard/prod/redis_password
      name: redis-password
