---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tpl-secrets
  namespace: prod
spec:
  backendType: systemManager
  data:
    - key: /clincard/prod/tpl_secrets_user
      name: username
    - key: /clincard/prod/tpl_secrets_password 
      name: password