apiVersion: v2
name: service
description: A Helm chart to define a generic structure for clincard microservices
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
- name: Developer Name
  email: developer@greenphire.com
keywords:
  - microservice