nameOverride: ccadmin
fullnameOverride: ccadmin
tier: frontend

image: 160116585046.dkr.ecr.us-east-1.amazonaws.com/clincard/ccadmin:5.3.6

dependencies:
  # -- Secrets dependency [couchdb-secret] (https://github.com/Greenphire/clincard-config/tree/uat/ccuat01/uat/secrets)
  couchdbsecret: couchdb-secret
  # -- Secrets dependency [nginx-cert] (https://github.com/Greenphire/clincard-config/tree/uat/ccuat01/uat/secrets)
  nginxcert: nginx-cert

# The below values can be overridden by parent chart global values. 
# See clincard chart values.yaml file.
# Start - chart global values
hosts:
  domain: clincard.com
  clincard: www.clincard.com
  static: static.clincard.com
  api: api-admin.clincard.com
  apiinternal: api-internal.clincard.com
  ccadmin: controlcenter.clincard.com
  ccalt: control-center.clincard.com
  ws: ws.clincard.com
# end - chart global values

volumes:
  configName: ccadmin-config
  configMountPath: /etc/nginx/conf.d
  configDefaultMode: 420
  envVarsName: ccadmin-env-vars
  envVarsMountPath: /usr/share/nginx/html/assets/env-config  

configMapJson:
  listen: 80
  
configMapEnvVarsJson:
  production: false   

service:
  enabled: true
  port: 80
  targetPort: 80

ingressCcadmin:
  enabled: true
  ingressClass: nginx

ingress:
  legacy-api:
    strip_path: false
    preserve_host: true
    service_name: clincard
    service_port: 8888
    path: /internal-api
    pathType: Prefix
    apiinternal: false
  configsvc:
    strip_path: true
    preserve_host: false
    service_name: configsvc
    service_port: 8080
    path: /configsvc
    pathType: Prefix
    apiinternal: false
  authsvc:
    strip_path: true
    preserve_host: false
    service_name: authsvc
    service_port: 8080
    path: /authsvc
    pathType: Prefix
    apiinternal: false
  rideshare:
    strip_path: true
    preserve_host: false
    service_name: rideshare-svc
    service_port: 8080
    path: /rideshare
    pathType: Prefix
    apiinternal: false
  api-internal:
    strip_path: true
    preserve_host: false
    service_name: tenninetynine
    service_port: 8080
    path: /ten99
    pathType: Prefix
    apiinternal: true

replicaCount: 3
autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5

serviceAccount:
  create: false 
  name: ""         

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler    
terminationGracePeriodSeconds: 30

rollingUpdateDeploymentStrategy:
  enabled: true
