---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "gravedigger.fullname" . }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "db" .|fromJson) "username" }}
      name: postgres-{{ get (include "db" .|fromJson) "username" }}
