apiVersion: v1
data:
  config.json: |
    {
        "gunicorn": {
            "bind": "0.0.0.0:8080",
            "workers": {{ ((.Values.gunicorn).workers) }},
            "timeout": 30,
            "limit_request_line": 0,
            "access_log_format": "remote!%({X-Forwarded-For}i)s|method!%(m)s|url-path!%(U)s|query!%(q)s|username!%(u)s|protocol!%(H)s|status!%(s)s|response-length!%(b)s|referrer!%(f)s|user-agent!%(a)s|request-time!%(L)s",
            "accesslog": "-",
            "logger_class": "jslog4kube.GunicornLogger"
        },
        "logging": {
            "version": 1,
            "disable_existing_loggers": false,
            "formatters": {
                "simple": {
                    "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
                }
            },
            "handlers": {
              "logstash": {
                    "class": "logstash.TCPLogstashHandler",
                    "host": "logstash-service.logging.svc.cluster.local",
                    "port": 5959,
                    "version": 1,
                    "tags": ["paymentdomain"]
               },
                "console": {
                    "class": "logging.StreamHandler",
                    "level": "INFO",
                    "formatter": "simple",
                    "stream": "ext://sys.stdout"
                },
                "info_file_handler": {
                    "class": "logging.handlers.RotatingFileHandler",
                    "level": "INFO",
                    "formatter": "simple",
                    "filename": "info.log",
                    "maxBytes": 10485760,
                    "backupCount": 20,
                    "encoding": "utf8"
                },
                "error_file_handler": {
                    "class": "logging.handlers.RotatingFileHandler",
                    "level": "ERROR",
                    "formatter": "simple",
                    "filename": "errors.log",
                    "maxBytes": 10485760,
                    "backupCount": 20,
                    "encoding": "utf8"
                }
            },
            "loggers": {
                "paymentdomain": {
                    "level": "INFO",
                    "handlers": ["logstash"],
                    "propagate": false
                },
                "paymentdomain_scripts": {
                    "level": "DEBUG",
                    "handlers": ["logstash"],
                    "propagate": false
                }
            },
            "root": {
                "level": "INFO",
                "handlers": ["logstash"]
            }
        }
    }
kind: ConfigMap
metadata:
  name: paymentdomain
