apiVersion: v1
kind: Service
metadata:
  labels:
    app: paymentdomain
    tmp: "true"
  name: paymentdomain-tmp
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: paymentdomain
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: paymentdomain
    tier: api
  type: NodePort
