{{- $usr := get (include "db" . | fromJson) "username" -}}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "service.fullname" . }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/postgres-{{ $usr }}
      name: postgres-{{ $usr }}
