name: tinvalidation
nameOverride: tinvalidation
fullnameOverride: tinvalidation

sovos_error_flag: false
real_validation: false

secretpath: lower
tier: api
replicas: 2
image: 160116585046.dkr.ecr.us-east-1.amazonaws.com/clincard/tinvalidation-service:1.1.0
revisionHistoryLimit: 10
progressDeadlineSeconds: 600
rollingUpdate:
  maxSurge: 10%
  maxUnavailable: 10%
resources:
  limits:
    cpu: 256m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64M
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /swagger.json
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

volumes:
- configMap:
    defaultMode: 420
    items:
    - key: config.json
      path: config.json
    name: tinvalidation
  name: config

serviceAccount:
  create: false
  name: ""

configMapJson:
  - dataKey: config.json
    dataKeyTemplateSrc: "/_configmap.json.tpl"
    loggerServiceName: tinvalidation
    gunicornTimeout: 60

dependencies:
  postgresadmin: postgres-admin
  # -- Secrets dependency [clincard](https://github.com/Greenphire/clincard-config/tree/uat/charts/clincard)
  clincardsecrets: clincard-secret
  redis: redis

# The below values can be overridden by parent chart global values. 
# See clincard chart values.yaml file.
postgres:
  image: bitnami/postgresql:11.6.0-debian-9-r0

db:
  service: microservicedb-postgres
  database: tinvalidation
  username: tinvalidation
  db_admin: clincard
