apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "tinvalidation.labels" . | nindent 4 }}
    tier: {{ .Values.tier }}
  name: {{ template "tinvalidation.fullname" . }}
spec:
  progressDeadlineSeconds: {{ default 600 .Values.progressDeadlineSeconds }}
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ default 10 .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "tinvalidation.fullname" . }}
      tier: {{ .Values.tier }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "tinvalidation.fullname" . }}
        tier: {{ .Values.tier }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        name: tinvalidation
        command: ["/bin/bash", "-c"]
        args:
          - "pip install python-logstash git+https://github.com/Greenphire/jslog4kube.git && tvs"
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: postgres-{{ include "db_usr" . }}
              name: {{ .Values.dependencies.clincardsecrets }}
        - name: DB_URI
          value: {{ printf "postgresql://%s:$(DB_PASS)@%s.%s/%s" (include "db_usr" .) (include "db_svc" .) .Release.Namespace (include "db_db" .) }}
        {{- if eq .Values.real_validation true }}
        - name: SOVOS_SID
          valueFrom:
            secretKeyRef:
              name: {{ template "tinvalidation.fullname" . }}
              key: sovos-sid
        - name: SOVOS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "tinvalidation.fullname" . }}
              key: sovos-client-id
        - name: SOVOS_ALIAS
          valueFrom:
            secretKeyRef:
              name: {{ template "tinvalidation.fullname" . }}
              key: sovos-alias
        - name: SOVOS_WSDL_URL
          value: {{ default "https://taxport.convey.com/WS/id.asmx?WSDL" (.Values.env).sovos_wsdl_url }}
        - name: TIN_VALIDATION_CLIENT_CLASS
          value: {{ default "tinvalidation.clients.SovosTINValidationClient" (.Values.env).tin_validation_client_class }}
        {{- end }}
        - name: SOVOS_ERROR_FLAG
          value: {{ .Values.sovos_error_flag | quote }}
        - name: REDIS_HOST
          value: {{ .Values.dependencies.redis }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: {{ .Values.dependencies.redis }}
        - name: CONFIG_FILE_PATH
          value: /config/config.json
        ports:
        - containerPort: 8080
          name: tinvalidation
          protocol: TCP
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ default "/config" .Values.containersVolumeMountsMountPath}}
          name: {{ default "config" .Values.containersVolumeMountsName}}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tinvalidation.serviceAccountName" . }}
