---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "tinvalidation.fullname" . }}
  labels: {{ include "tinvalidation.labels" . | nindent 4 }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/sovos-sid
      name: sovos-sid
    - key: /clincard/{{ .Values.secretpath }}/sovos-client-id
      name: sovos-client-id
    - key: /clincard/{{ .Values.secretpath }}/sovos-alias
      name: sovos-alias
