{{- $pusr := get (include "portaldb" . | fromJson) "username" -}}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "programbalancedetail.fullname" . }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/postgres-{{ $pusr }}
      name: postgres-{{ $pusr }}
    - key: /clincard/{{ .Values.secretpath }}/mediaserver_key
      name: id_rsa
    - key: /clincard/{{ .Values.secretpath }}/sendgrid-api-key
      name: sendgrid-api-key
