---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "authsvc.fullname" . }}
  labels: {{ include "authsvc.labels" . | nindent 4 }}
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/jwt_secret
    name: jwt-secret
  - key: /clincard/{{ .Values.secretpath }}/redis_password
    name: redis-password
