apiVersion: v2
name: configsvc
description: Helm chart with the configsvc definition
type: application
version: 0.2.7
appVersion: "1.0"
maintainers:
- name: Helene McElroy
  email: helene.mcelroy@greenphire.com
- name: Jeisson Osorio
  email: jeisson.osorio@greenphire.com
keywords:  
  - configsvc
