nameOverride: configsvc
fullnameOverride: configsvc
tier: api

image: 160116585046.dkr.ecr.us-east-1.amazonaws.com/clincard/config-service:3.1.2

dependencies:
  # -- Secrets dependency [couchdb-secret] (https://github.com/Greenphire/clincard-config/tree/uat/ccuat01/uat/secrets)
  couchdbsecret: couchdb-secret
  messagesvc:
    name: message-service
    port: 8080

# The below values can be overridden by parent chart global values. 
# See clincard chart values.yaml file.
# Start - chart global values
couchdb:
  user: admin
  service: couchdb-ha-svc-couchdb
  db_configs: configs
  db_payment: payments
  db_taxmanagement: taxmgt
  db_flexpayopts: flexible_payment_options
  initdb: false
  init_bucket: cc-couchinit-lower
# end - chart global values

volumes:
  configName: config
  configMountPath: /config
  configDefaultMode: 420  

configMapJson:
- dataKey: config.json
  dataKeyTemplateSrc: "/_configmap.json.tpl"
  loggerServiceName: configsvc
  gunicornBlock: true

service:
  enabled: true
  type: ClusterIP  
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

replicaCount: 3
autoscaling:
  enabled: false
  minReplicas: 5
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /swagger.json
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /swagger.json
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
  
serviceAccount:
  create: false 
  name: ""         

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler    
terminationGracePeriodSeconds: 30

rollingUpdateDeploymentStrategy:
  enabled: true
