---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "paymentevents.fullname" . }}
  labels: {{ include "paymentevents.labels" . | nindent 4 }}
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/rabbit_userpass
    name: {{ .Values.dependencies.rabbitmqSecrets }}
