{{- if and .Values.autoscaling .Values.autoscaling.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "paymentprocessor.fullname" . }}-rabbitmq-scaledobject
  labels: {{ include "paymentprocessor.labels" . | nindent 4 }}
spec:
  scaleTargetRef: {{ include "paymentprocessor.autoscaling.scaleTargetRef" . | nindent 4 }}
  minReplicaCount: {{ default 2 .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ default 10 .Values.autoscaling.maxReplicas }}
  pollingInterval: {{ default 30 .Values.autoscaling.pollingInterval }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: {{ default 1 .Values.autoscaling.podsPerScaling }}
            periodSeconds: {{ default 60 .Values.autoscaling.scalingUpInterval }}
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: {{ default 1 .Values.autoscaling.podsPerScaling }}
            periodSeconds: {{ default 60 .Values.autoscaling.scalingDownInterval }}
  triggers:
  - type: rabbitmq
    metricType: Value
    metadata: {{ include "paymentprocessor.autoscaling.triggerMetadata" . | nindent 6 }}
{{- end }}