---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "paymentprocessor.fullname" . }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/postgres-{{ include "pusr" . }}
      name: postgres-{{ include "pusr" . }}
