apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: uat
spec:
  interval: 60m
  url: https://charts.helm.sh/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbit
  namespace: uat
spec:
  interval: 60m
  chart:
    spec:
      chart: rabbitmq-ha
      version: "1.34.1"
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: uat
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: rabbitmq-secrets
      valuesKey: SecureString
  values:
    image:
      repository: rabbitmq
      tag: 3.7.21-management-alpine
    replicaCount: 1
    rabbitmqUsername: admin
    definitions:
      vhosts: |-
        {
          "name": ""
        },
        {
          "name": "celery"
        }
      permissions: |-
        {
          "user": "payments",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "celery",
          "vhost": "celery",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      policies: |-
        {
          "name": "ha",
          "pattern": "",
          "vhost": "/",
          "definition": {
            "ha-mode": "all",
            "ha-sync-mode": "automatic"
          }
        },
        {
           "name": "ha-celery",
           "pattern": "",
           "vhost": "celery",
           "definition": {
             "ha-mode": "all",
             "ha-sync-mode": "automatic"
           }
         }
    managementUsername: management
    busyboxImage:
      repository: busybox
      tag: latest
      pullPolicy: Always
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
    persistentVolume:
      enabled: true
      name: data
      accessModes:
      - ReadWriteOnce
      size: 8Gi
    podAntiAffinity: hard
    prometheus:
      exporter:
        enabled: false
      operator:
        enabled: false