---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: uat
spec:
  interval: 60m
  upgrade:
    timeout: 10m
  chart:
    spec:
      chart: charts/redis
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: clincard-uat
        namespace: flux-system