# Headless service for stable DNS entries of StatefulSet members.
{{ if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.port }}
  clusterIP: None
  selector:
    app: {{ .Values.name }}
{{ end }}