{{- if .Values.enabled }}
{{- if ne .Release.Namespace "prod" }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{ include "datasupport.labels" . | nindent 4 }}
  name: {{ template "datasupport.fullname" . }}
rules:
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["get", "create"]
{{- end }}
{{- end }}