{{- if .Values.enabled }}
{{- if ne .Release.Namespace "prod" }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  labels: {{ include "datasupport.labels" . | nindent 4 }} 
  name: {{ template "datasupport.secrets" . }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/fisdev-user
      name: fisdev-user
    - key: /clincard/{{ .Values.secretpath }}/fisdev-cred
      name: fisdev-cred
{{- end }}
{{- end }}