{{- if .Values.enabled }}
{{- if ne .Release.Namespace "prod" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: {{ include "datasupport.labels" . | nindent 4 }} 
    component: {{ template "datasupport.ingress.fullname" . }}
  name: {{ template "datasupport.ingress.fullname" . }}
spec:
  ingressClassName: {{ default "internal" .Values.ingressClass }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "datasupport.fullname" . }}
            port:
              number: {{ default 5000 .Values.service.port }}
    host: {{ include "hosts_datasupport" . }}
  tls:
  - secretName: {{ default "nginx-cert" .Values.TlsSecretName }}
    hosts:
    - {{ include "hosts_datasupport" . }}
{{- end }}
{{- end }}