{{- if and .Values.enabled .Values.serviceAccount.create }}
{{- if ne .Release.Namespace "prod" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datasupport.serviceAccountName" . }}
  labels: {{- include "datasupport.labels" $ | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
{{- end }}
{{- end }}