---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "service.fullname" . }}
  labels: {{ include "service.labels" . | nindent 4 }} 
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/jwt_secret
    name: jwt-secret
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ include "db_usr" . }}
    name: postgres-{{ include "db_usr" . }}
  - key: /clincard/{{ .Values.secretpath }}/redis_password
    name: redis-password