{{- if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsreports.fullname" . }}
  labels: {{ include "dsreports.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ template "dsreports.fullname" . }}
    tier: {{ .Values.service.tier }} 
  ports:    
    - name: {{ default "http" .Values.service.portName | quote }}
      port: {{ default 8080 .Values.service.port }}
      protocol: {{ default "TCP" .Values.service.protocol }}
      targetPort: {{ default 8080 .Values.service.targetPort }}
  sessionAffinity: {{ default "None" .Values.service.sessionAffinity }}
  type: {{ default "ClusterIP" .Values.service.type }}
{{- end }}
