nameOverride: subject-svc
fullnameOverride: subject-svc
secretpath: lower
tier: api

image: 160116585046.dkr.ecr.us-east-1.amazonaws.com/clincard/subject-service:2.0.0

# The below values can be overridden by parent chart global values. 
# See clincard chart values.yaml file.
# Start - chart global values
postgres:
  image: bitnami/postgresql:11.6.0-debian-9-r0

portaldb:
  service: portaldb-postgres
  database: ccportaldatabase
  username: subjectsvc
  db_admin: clincard

dependencies:
  authsvc: authsvc
# end - chart global values

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler
securityContext: {}
terminationGracePeriodSeconds: 30

volumes:
  - name: config
    configMap:
      defaultMode: 420    
      name: subject-svc
      items:
        - key: config.json
          path: config.json

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /swagger.json
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /swagger.json
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5

configMapJson:
  - dataKey: config.json
    dataKeyTemplateSrc: "/_configmap.json.tpl"
    loggerServiceName: subjectsvc    

service:
  enabled: true  
  port: 8080  
  protocol: TCP
  targetPort: 8080

replicaCount: 2
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccount:
  create: false 
  name: ""

rollingUpdateDeploymentStrategy:
  enabled: true
  maxSurge:
  maxUnavailable:
