---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "websocketssvc.fullname" . }}
  labels: {{ include "websocketssvc.labels" . | nindent 4 }} 
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/websocket-secret
    name: websocket-secret