name: paymentindex-consumer
nameOverride: paymentindex-consumer
fullnameOverride: paymentindex-consumer
tier: payments

image: 160116585046.dkr.ecr.us-east-1.amazonaws.com/clincard/paymentindex-consumer:1.4.1

resources:
  consumer:
    replicas: 2
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 125m
      memory: 64Mi
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 6
      rabbitmqMetricName: paymentindex-queue-length
      rabbitmqQueueName: paymentindex
      rabbitmqTargetValue: 10
      rabbitmqUrlEnvVar: RABBITMQ_URI

# The below values can be overridden by parent chart global values. 
# See clincard chart values.yaml file.
couchdb:
  service: couchdb-ha-svc-couchdb
  user: admin
  db_pis: paymentindex
  db_pbdr: pbdr_v2
  initdb: false
  init_bucket: cc-couchinit-lower

postgres:
  image: bitnami/postgresql:11.6.0-debian-9-r0

db:
  service: paymentdb-postgres
  database: paymentindex
  username: paymentindex
  db_admin: clincard

portaldb:
  service: portaldb-postgres
  database: ccportaldatabase
  username: paymentindex
  db_admin: clincard

rabbit:
  username: payments
  service: rabbit-rabbitmq-ha
