---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subjectsvc.fullname" . }}
  labels: {{ include "subjectsvc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "subjectsvc.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: {{ default 600 .Values.progressDeadlineSeconds  }}
  revisionHistoryLimit: {{ default 10 .Values.revisionHistoryLimit  }}
  {{- if .Values.rollingUpdateDeploymentStrategy.enabled }}
  strategy: 
    type: RollingUpdate
    rollingUpdate: {{ include "subjectsvc.rollingUpdateDeploymentStrategy" . | nindent 6 }}
  {{- end }}
  template:
    metadata:
      labels: {{ include "subjectsvc.selectorLabels" . | nindent 8 }}        
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
      - name: wait-for-authsvc
        image: alpine:3.7
        command: ["sh", "-c", "apk add curl && until curl --fail --connect-timeout 5 http://{{ .Values.dependencies.authsvc }}.{{ .Release.Namespace }}:8080/swagger.json; do sleep 2; done"]
      containers:
      - name: {{ include "subjectsvc.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy }}
        command: ["/bin/bash"]  
        args:
        - -c
        - pip install python-logstash git+https://github.com/Greenphire/jslog4kube.git && subject-service
        ports:
        - containerPort: {{ default 8080 .containerPort }}
          name: {{ include "subjectsvc.fullname" . }}
          protocol: {{ default "TCP" .containerPortProtocol }}
        env: {{ include "opentelemetry_envs" . | nindent 8 -}}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: postgres-{{ include "portaldb_pusr" . }}
              name: {{ template "subjectsvc.fullname" . }}
        - name: DB_URI
          value: {{ printf "postgresql://%s:$(DB_PASS)@%s.%s/%s" (include "portaldb_pusr" .) (include "portaldb_psvc" .) .Release.Namespace (include "portaldb_pdb" .) }}
        - name: AUTH_BASE_URI
          value: http://{{ .Values.dependencies.authsvc }}.{{ .Release.Namespace }}:8080
        - name: SERVICE_UUID
          value: C2E88FD7-B275-40A8-A6B1-E6213B28CF7F
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: {{ .Values.dependencies.authsvc }}
        - name: CONFIG_FILE_PATH
          value: /config/config.json  
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
        resources:
          limits:
            cpu: {{ default "256m" .Values.resourcesLimitsCpu }}
            memory: {{ default "256Mi" .Values.resourcesLimitsMemory }}
          requests:
            cpu: {{ default "10m" .Values.resourcesRequestsCpu }}
            memory: {{ default "64Mi" .Values.resourcesRequestsMemory }}
        terminationMessagePath: {{ default "/dev/termination-log" .Values.containersTerminationMessagePath}}
        terminationMessagePolicy: {{ default "File" .Values.containersTerminationMessagePolicy}}
        volumeMounts:
        - mountPath: {{ default "/config" .Values.containersVolumeMountsMountPath}}
          name: {{ default "config" .Values.containersVolumeMountsName}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "subjectsvc.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
