---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secrets
  namespace: ##namespace##
spec:
  backendType: systemManager
  data:
    - key: /clincard/##environment##/couchdb_secrets
      name: SecureString
 