---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret 
  namespace: ##namespace##
spec:
  backendType: systemManager
  data:
    - key: /clincard/##environment##/couchpass
      name: password
