---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: nginx-cert
  namespace: ##namespace##
spec:
  backendType: systemManager
  data:
    - key: /clincard/common/nginx-cert
      name: tls.crt
    - key: /clincard/common/nginx-key
      name: tls.key
