---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
  namespace: ##namespace##
spec:
  backendType: systemManager
  data:
    - key: /clincard/##environment##/rabbitmq_secrets
      name: SecureString
