---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rabbit-secret 
  namespace: ##namespace##
spec:
  backendType: systemManager
  data:
    - key: /clincard/##environment##/rabbit_userpass
      name: payments
    - key: /clincard/##environment##/rabbit_userpass
      name: celery
