---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: redis
  namespace: ##namespace##
spec:
  backendType: systemManager
  data:
    - key: /clincard/##environment##/redis-password
      name: redis-password
