---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
  namespace: uat
spec:
  backendType: systemManager
  data:
    - key: /clincard/preprod/couchpass
      name: password
