---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rabbit-secret 
  namespace: uat
spec:
  backendType: systemManager
  data:
    - key: /clincard/preprod/rabbit_userpass
      name: payments
    - key: /clincard/preprod/rabbit_userpass
      name: celery
