---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
  namespace: uat
spec:
  backendType: systemManager
  data:
    - key: /clincard/preprod/rabbitmq_secrets
      name: SecureString
