apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: redis
  namespace: uat
spec:
  backendType: systemManager
  data:
    - key: /clincard/preprod/redis_password
      name: redis-password
