---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: memcached
  namespace: ##namespace##
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: memcached
  chart:
    repository: https://charts.helm.sh/stable
    name: memcached
    version: 3.2.3
  values:
    image: memcached:1.5.6-alpine
    replicaCount: 2
