---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbit
  namespace: ##namespace##
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: rabbit
  chart:
    repository: https://charts.helm.sh/stable
    name: rabbitmq-ha
    version: 1.34.1
  valuesFrom:
  - secretKeyRef:
      name: rabbitmq-secrets
      key: SecureString
  values:
    image:
      repository: rabbitmq
      tag: 3.7.21-management-alpine
    ingress:
      enabled: true
      hostName: ##instance##-rabbit.clincard.com
      tls: true
      tlsSecret: nginx-cert
    replicaCount: 2
    rabbitmqUsername: admin
    definitions:
      vhosts: |-
        {
          "name": ""
        },
        {
          "name": "celery"
        }
      permissions: |-
        {
          "user": "payments",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "celery",
          "vhost": "celery",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      policies: |-
        {
          "name": "ha",
          "pattern": "",
          "vhost": "/",
          "definition": {
            "ha-mode": "all",
            "ha-sync-mode": "automatic"
          }
        },
        {
           "name": "ha-celery",
           "pattern": "",
           "vhost": "celery",
           "definition": {
             "ha-mode": "all",
             "ha-sync-mode": "automatic"
           }
         }
    managementUsername: management
    busyboxImage:
      repository: busybox
      tag: latest
      pullPolicy: Always
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
    persistentVolume:
      enabled: true
      name: data
      accessModes:
      - ReadWriteOnce
      size: 8Gi
    podAntiAffinity: hard
    prometheus:
      exporter:
        enabled: false
      operator:
        enabled: false
