---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rideshare.consumer.fullname" . }}
  labels: {{ include "rideshare.consumer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "rideshare.consumer.selectorLabels" . | nindent 6 }}
  {{- if not .Values.rideshareConsumer.autoscaling.enabled }}
  replicas: {{ .Values.rideshareConsumer.replicaCount }}
  {{- end }}
  progressDeadlineSeconds: {{ default 600 .Values.progressDeadlineSeconds  }}
  revisionHistoryLimit: {{ default 10 .Values.revisionHistoryLimit  }}
  {{- if .Values.rollingUpdateDeploymentStrategy.enabled }}
  strategy: 
    type: RollingUpdate
    rollingUpdate: {{ include "rideshare.rollingUpdateDeploymentStrategy" . | nindent 6 }}
  {{- end }}
  template:
    metadata:
      labels: {{ include "rideshare.consumer.selectorLabels" . | nindent 8 }}        
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ include "rideshare.consumer.fullname" . }}
        image: {{ .Values.rideshareConsumer.image }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy }}
        command: ["/bin/bash"]
        args:
        - -c
        - pip install python-logstash git+https://github.com/Greenphire/jslog4kube.git && ridesharesvc-consumer        
        env: 
        - name: CONFIG_FILE_PATH
          value: {{.Values.envs.configFilePath }}
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: postgres-{{ include "db_usr" . }}
              name: {{ .Values.dependencies.clincardsecrets }}
        - name: DB_URI
          value: {{ printf "postgresql://%s:$(DB_PASS)@%s.%s/%s" (include "db_usr" .) (include "db_svc" .) .Release.Namespace (include "db_db" .) }}
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              key: payments
              name: {{ .Values.dependencies.rabbitsecret }}
        - name: RABBITMQ_URI
          value: {{ printf "amqp://%s:$(RABBIT_PASS)@%s.%s:5672/" (include "rmq_usr" .) (include "rmq_svc" .) .Release.Namespace }}
        - name: RABBITMQ_EXCHANGE
          value: {{.Values.envs.rabbitmqExchange }}
        - name: RABBITMQ_QUEUE
          value: {{.Values.envs.rabbitmqQueue }}
        - name: RABBITMQ_ROUTING_KEY
          value: {{.Values.envs.rabbitmqRoutingKey }}
        - name: RABBITMQ_RETRIES
          value: {{.Values.envs.rabbitmqRetries | quote }}
        resources:
          {{- toYaml .Values.rideshareConsumer.resources | nindent 10 }}          
        terminationMessagePath: {{ default "/dev/termination-log" .Values.containersTerminationMessagePath}}
        terminationMessagePolicy: {{ default "File" .Values.containersTerminationMessagePolicy}}
        volumeMounts:
        - mountPath: {{ default "/config" .Values.volumes.configMountPath }}
          name: {{ default "config" .Values.volumes.configName }}        
      serviceAccountName: {{ include "rideshare.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      volumes:
      - name: {{ default "config" .Values.volumes.configName }}
        configMap:
          defaultMode: {{ default 420 .Values.volumes.configDefaultMode }}
          name: {{ include "rideshare.svc.fullname" . }}
          items:
          - key: config.json
            path: config.json