---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rideshare.secrets" . }}
  labels: {{ include "rideshare.labels" . | nindent 4 }} 
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/rideshare-aws-access-key
    name: aws-access-key
  - key: /clincard/{{ .Values.secretpath }}/rideshare-aws-secret-key
    name: aws-secret-key
  - key: /clincard/{{ .Values.secretpath }}/lyft-client-id
    name: lyft-client-id
  - key: /clincard/{{ .Values.secretpath }}/lyft-client-secret
    name: lyft-client-secret
  - key: /clincard/{{ .Values.secretpath }}/lyft-refresh-token
    name: lyft-refresh-token
  - key: /clincard/{{ .Values.secretpath }}/rideshare-websocket-secret
    name: websocket-secret