---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "paymentgateway.fullname" . }}
  labels: {{ include "paymentgateway.labels" . | nindent 4 }} 
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ include "db_usr" . }}
    name: postgres-{{ include "db_usr" . }}
  - key: /clincard/{{ .Values.secretpath }}/rabbit_userpass
    name: {{ .Values.dependencies.rabbitmqSecrets }}
  - key: /clincard/{{ .Values.secretpath }}/redis_password
    name: redis-password
{{- if ne (include "portaldb_pusr" .) (include "db_usr" .) }}
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ include "portaldb_pusr" . }}
    name: postgres-{{ include "portaldb_pusr" . }}
{{- end }}