---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "paymentindex.fullname" . }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "db" . | fromJson) "username" }}
      name: postgres-{{ get (include "db" . | fromJson) "username" }}
    {{- if ne (get (include "portaldb" . | fromJson) "username") (get (include "db" . | fromJson) "username") }}
    - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "portaldb" . | fromJson) "username" }}
      name: postgres-{{ get (include "portaldb" . | fromJson) "username" }}
    {{- end }}
    - key: /clincard/{{ .Values.secretpath }}/payment_decryption_key
      name: decryptionkey
