---
{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "couchdb.fullname" . }}-ext
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: {{ template "couchdb.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: 5984
      targetPort: 5984
  type: LoadBalancer
  {{- end -}}
