{{- if eq .Values.ccsshsecrets.enabled true }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cc-ssh-key
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ default .Values.secretpath .Values.ccsshsecrets.secretpath }}/cc-ssh-key-id_rsa
      name: id_rsa    
    - key: /clincard/{{ default .Values.secretpath .Values.ccsshsecrets.secretpath }}/cc-ssh-key-known_hosts
      name: known_hosts
{{- end }}