{{- if eq .Values.clincardclincard.enable true }}
{{- $deployment := .Values.clincardclincard }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "service.fullname" . }}
  annotations:
    # This will re-map any /endpoint to /
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: {{ .Values.ingress.enableCors | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-SSL-Protocol $ssl_protocol;
      proxy_set_header X-Scheme $scheme;
      proxy_set_header X-Forwarded-Proto $scheme;      
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.class }}
  rules:
  - host: {{ include "hosts_cc" . }}
    http: &http_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "service.fullname" . }}
            port:
              number: {{ default 8888 $deployment.service.port }}
  - host: {{ include "hosts_domain" . }}
    http: *http_rules
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    hosts:
    - {{ include "hosts_cc" . }}
    - {{ include "hosts_domain" . }}
{{- end }}
