{{- if eq .Values.clincardsecrets.enable true }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "service.secret" . }}-pre-hook
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  backendType: systemManager
  data:
{{- range $item := .Values.clincardsecrets.keys }}
    - key: {{ $item.key }}
      name: {{ $item.name }}
{{- end }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ template "service.secret" . }}
spec:
  backendType: systemManager
  data:
{{- range $item := .Values.clincardsecrets.keys }}
    - key: {{ $item.key }}
      name: {{ $item.name }}
{{- end }}
{{- end }}