{{- if eq .Values.fisgpgsecrets.enabled true }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: fis-gpg-key  
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ default .Values.secretpath .Values.fisgpgsecrets.secretpath }}/fis-gpg-key-fis_pub_key.asc
      name: fis_pub_key.asc
{{- end }}