{{- if eq .Values.fissshsecrets.enabled true }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: fis-ssh-key
spec:
  backendType: systemManager
  data:
{{- range $item := .Values.fissshsecrets.keys }}
    - key: {{ $item.key }}
      name: {{ $item.name }}
{{- end }}
{{- end }}