{{- if eq .Values.jupyter.enable true }}
{{- if .Values.jupyter.external }}
{{- $deployment := .Values.jupyter }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "service.jupyter.fullname" . }}
  annotations:
    # This will re-map any /endpoint to /
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: {{ .Values.ingress.enableCors | quote }}
    nginx.ingress.kubernetes.io/cors-allow-origin: "*.{{ include "hosts_domain" . }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-SSL-Protocol $ssl_protocol;
      proxy_set_header X-Scheme $scheme;
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.class }}
  rules:
  - host: {{ include "hosts_jupyter" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "service.jupyter.fullname" . }}
            port:
              number: {{ default 8080 $deployment.service.port }}          
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    hosts:
      - {{ include "hosts_jupyter" . }}
{{- end }}
{{- end }}