{{- if eq .Values.clincardclincard.enable true }}
{{- if eq .Release.Namespace "prod" }}
{{- $deployment := .Values.clincardclincard }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $deployment.myclincardIngress.secretName }}
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/myclincard-cert
      name: myclincard-cert    
    - key: /clincard/{{ .Values.secretpath }}/myclincard-key
      name: myclincard-key
{{- end }}
{{- end }}