{{- if eq .Values.passwordmanagersecrets.enabled true }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: password-manager
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ default .Values.secretpath .Values.passwordmanagersecrets.secretpath }}/pmp-token
      name: token
    - key: /clincard/{{ default .Values.secretpath .Values.passwordmanagersecrets.secretpath }}/pmp-key
      name: clincard_pmp.key
    - key: /clincard/{{ default .Values.secretpath .Values.passwordmanagersecrets.secretpath }}/pmp-crt
      name: clincard_pmp.crt
{{- end }} 