---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: postgres-admin-pre-hook
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "hook-succeeded,hook-failed"
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "db" . | fromJson) "db_admin" }}
    name: admin-microservicedb-{{ get (include "db" . | fromJson) "db_admin" }}
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "portaldb" . | fromJson) "db_admin" }}
    name: admin-portaldb-{{ get (include "portaldb" . | fromJson) "db_admin" }}
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "paymentdb" . | fromJson) "db_admin" }}
    name: admin-paymentdb-{{ get (include "paymentdb" . | fromJson) "db_admin" }}

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: postgres-admin
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "db" . | fromJson) "db_admin" }}
    name: admin-microservicedb-{{ get (include "db" . | fromJson) "db_admin" }}
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "portaldb" . | fromJson) "db_admin" }}
    name: admin-portaldb-{{ get (include "portaldb" . | fromJson) "db_admin" }}
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ get (include "paymentdb" . | fromJson) "db_admin" }}
    name: admin-paymentdb-{{ get (include "paymentdb" . | fromJson) "db_admin" }}
