{{- if .Values.external -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ get (include "db" . | fromJson) "service" }}-pre-hook
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "hook-succeeded,hook-failed"
spec:
  externalName: {{ get (include "db" . | fromJson) "host" }}
  sessionAffinity: None
  type: ExternalName
---
kind: Service
apiVersion: v1
metadata:
  name: {{ get (include "portaldb" . | fromJson) "service" }}-pre-hook
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "hook-succeeded,hook-failed"
spec:
  externalName: {{ get (include "portaldb" . | fromJson) "host" }}
  sessionAffinity: None
  type: ExternalName
---
kind: Service
apiVersion: v1
metadata:
  name: {{ get (include "paymentdb" . | fromJson) "service" }}-pre-hook
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: "hook-succeeded,hook-failed"
spec:
  externalName: {{ get (include "paymentdb" . | fromJson) "host" }}
  sessionAffinity: None
  type: ExternalName
---
kind: Service
apiVersion: v1
metadata:
  name: {{ get (include "db" . | fromJson) "service" }}
spec:
  externalName: {{ get (include "db" . | fromJson) "host" }}
  sessionAffinity: None
  type: ExternalName
---
kind: Service
apiVersion: v1
metadata:
  name: {{ get (include "portaldb" . | fromJson) "service" }}
spec:
  externalName: {{ get (include "portaldb" . | fromJson) "host" }}
  sessionAffinity: None
  type: ExternalName
---
kind: Service
apiVersion: v1
metadata:
  name: {{ get (include "paymentdb" . | fromJson) "service" }}
spec:
  externalName: {{ get (include "paymentdb" . | fromJson) "host" }}
  sessionAffinity: None
  type: ExternalName
{{- end -}}
