---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "milestonesvc.fullname" . }}
  labels: {{ include "milestonesvc.labels" . | nindent 4 }}
spec:
  backendType: systemManager
  data:
  - key: /clincard/{{ .Values.secretpath }}/postgres-{{ include "portaldb_pusr" . }}
    name: postgres-{{ include "portaldb_pusr" . }}