---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ (include "dsreplicator.fullname" .) }}-credentials-aws
spec:
  backendType: systemManager
  data:
    - key: /clincard/{{ .Values.secretpath }}/DS_DB_AWS_USER
      name: user
    - key: /clincard/{{ .Values.secretpath }}/DS_DB_AWS_PASSWORD
      name: password
