{{- if .Values.longterm.enabled }}
{{- $cronjob := .Values.longterm }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjob.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ $cronjob.name }}
{{ include "dsreplicator.labels" . | indent 4 }}
spec:
  successfulJobsHistoryLimit: {{ default .Values.historyLimits.successfulJobsHistoryLimit $cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default .Values.historyLimits.failedJobsHistoryLimit $cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ default .Values.concurrencyPolicy $cronjob.concurrencyPolicy }}  
  schedule: {{ $cronjob.schedule | quote }}
  suspend: {{ default .Values.suspend $cronjob.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ default "task" $cronjob.containersName }}
            image: {{ default .Values.image $cronjob.image}}
            imagePullPolicy: {{ default .Values.imagePullPolicy $cronjob.imagePullPolicy}}
            command: ["bin/sh", "-c"]
            args: {{ toJson $cronjob.args }}
            env: {{ include (print .Template.BasePath "/_commons_env.yaml.tpl" ) . |  nindent 14 }}
            resources:
              limits:
                cpu: {{ default .Values.resources.limits.cpu $cronjob.resourcesLimitsCpu | quote }}
                memory: {{ default .Values.resources.limits.memory $cronjob.resourcesLimitsMemory | quote }}
              requests:
                cpu: {{ default .Values.resources.requests.cpu $cronjob.resourcesRequestsCpu | quote }}
                memory: {{ default .Values.resources.requests.memory $cronjob.resourcesRequestsMemory | quote }} 
            volumeMounts:
            - mountPath: {{ default "/config" .Values.containersVolumeMountsMountPath}}
              name: {{ default "config" .Values.containersVolumeMountsName}}
          {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          hostAliases:
{{- range $cronjob.hostAliases }}
          - hostnames: {{ .names | toYaml | nindent 12 }}
            ip: {{ .ip }}
{{- end }}           
          restartPolicy: {{ default .Values.restartPolicy $cronjob.restartPolicy}}
          schedulerName: {{ default .Values.schedulerName $cronjob.schedulerName}}
          {{- with $cronjob.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}          
{{- end }}
