{{- if .Values.batchProcessorSftp.enabled }}
{{- $cronjob := .Values.batchProcessorSftp}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjob.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ $cronjob.name }}
{{ include "cronjobs.labels" . | indent 4 }}
spec:
  successfulJobsHistoryLimit: {{ default .Values.historyLimits.successfulJobsHistoryLimit $cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default .Values.historyLimits.failedJobsHistoryLimit $cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ default "Allow" $cronjob.concurrencyPolicy }}  
  schedule: {{ $cronjob.schedule | quote }}
  suspend: {{ default .Values.suspend $cronjob.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ default "task" $cronjob.containersName }}
            image: {{ default .Values.image $cronjob.image}}
            imagePullPolicy: {{ default .Values.imagePullPolicy $cronjob.imagePullPolicy}}
            args: {{ toJson $cronjob.args }}
            env:              
{{ include (print .Template.BasePath "/_commons_env.yaml.tpl" ) . |  indent 14 }}
{{ include (print .Template.BasePath "/_commons_xfr_env.yaml.tpl" ) . |  indent 14 }}
{{- range $key, $value := $cronjob.customEnv }}
              - name: {{ $key }}
                value: {{ $value | quote }}
{{- end }}
{{- range $key, $value := $cronjob.customCCSecretsEnv }}
              - name: {{ $key }}
                valueFrom:
                  secretKeyRef:
                    key: {{ $value }}
                    name: {{ $.Values.dependencies.clincardsecrets }}
{{- end }}
              - name: PAYMENT_DOMAIN_SWAGGER
                value: 'http://{{ .Values.dependencies.paymentdomain }}.{{ .Release.Namespace }}:8080/swagger.json'
              - name: PAYMENT_EVENTS_SWAGGER
                value: 'http://{{ .Values.dependencies.paymentevents }}.{{ .Release.Namespace }}:8080/swagger.json'
              - name: RABBIT_CELERY_PASS
                valueFrom:
                  secretKeyRef:
                    key: celery
                    name: {{ .Values.dependencies.rabbitsecrets }}
              - name: CELERY_RABBITMQ_URL
                value: {{ printf "amqp://%s:$(RABBIT_CELERY_PASS)@%s.%s:5672/celery" (include "cel_usr" .) (include "cel_svc" .) .Release.Namespace }}
              - name: RABBITMQ_URL
                value: {{ printf "amqp://%s:$(RABBIT_PASS)@%s.%s:5672/" (include "rmq_usr" .) (include "rmq_svc" .) .Release.Namespace }}
              - name: RABBITMQ_HTTP_URL
                value: {{ printf "http://%s:$(RABBIT_ADMIN_PASS)@%s.%s:15672" (include "rmq_adminusr" .) (include "rmq_svc" .) .Release.Namespace }}
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    key: postgres-{{ include "db_usr" . }}
                    name: {{ .Values.dependencies.paymentdomainsecrets}}
              - name: DOMAIN_DB_URI
                value: {{ printf "postgresql://%s:$(DB_PASS)@%s.%s/%s" (include "db_usr" .) (include "db_svc" .) .Release.Namespace $cronjob.database }}              
            resources:
              limits:
                cpu: {{ default .Values.resources.limits.cpu $cronjob.resourcesLimitsCpu }}
                memory: {{ default .Values.resources.limits.memory $cronjob.resourcesLimitsMemory }}
              requests:
                cpu: {{ default .Values.resources.requests.cpu $cronjob.resourcesRequestsCpu }}
                memory: {{ default .Values.resources.requests.memory $cronjob.resourcesRequestsMemory }}
            terminationMessagePath: {{ default "/dev/termination-log" $cronjob.terminationMessagePath}}
            terminationMessagePolicy: {{ default "File" $cronjob.terminationMessagePolicy}}
            volumeMounts:
            - mountPath: {{ .Values.volumes.ccSshMountPath }}
              name: {{ .Values.volumes.ccSshName }}
            - mountPath: {{ .Values.volumes.pgpMountPath }}
              name: {{ .Values.volumes.pgpName }}
            workingDir: {{ default "/clincard/src/greenphire" $cronjob.workingDir }}
          dnsPolicy: {{ default "ClusterFirst" $cronjob.dnsPolicy }}
          restartPolicy: {{ default .Values.restartPolicy $cronjob.restartPolicy}}
          schedulerName: {{ default .Values.schedulerName $cronjob.schedulerName}}
          {{- with $cronjob.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: {{ .Values.volumes.ccSshName }}
            secret:
              defaultMode: {{ default .Values.volumes.ccSshDefaultMode $cronjob.ccSshDefaultMode }}
              secretName: {{ .Values.dependencies.ccsshsecrets }}
          - name: {{ .Values.volumes.pgpName }}
            persistentVolumeClaim:
              claimName: {{ printf (.Values.volumes.pgpClaim) $.Release.Namespace }}          
{{- end }} 
