name: Helm validation

on: [push, pull_request]

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./helm-check-action-sample
        CHART_VALUES: ./helm-check-action-sample/values/test.yaml